#!/bin/bash


#lib location
lib_loc=/usr/local/lib/alt_ls
#lib file name
lib_bin_id="alt_ls"


args=$(ls)

#check if file exist in debug verison 
if [ -f build/$lib_bin_id ]; then 
	
	res=$(build/./alt_ls $args)
	echo $res
elif [ -f $lib_loc/$lib_bin_id ]; then
	res=$($lib_loc/./alt_ls $args)
	echo $res
else
	echo "cannot find binary file"
	exit 1
fi


